language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
install:
- apt-get install -y tree
- ./gradlew assemble
script:
- ./gradlew build
before_deploy:
- "echo 'ready?'"
- zip -r latest *
- mkdir -p cd_upload
- mv latest.zip cd_upload/latest.zip
- tree
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: hwangdezang
  skip_cleanup: true
  local_dir: cd_upload
  upload-dir: travis
  on:
    branch: master