language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
install:
- sudo apt-get install tree -y
- ./gradlew assemble
script:
- ./gradlew build
before_deploy:
- "echo 'ready?'"
- zip -r latest *
- mkdir -p s3_upload
- mv latest.zip s3_upload/latest.zip
- tree
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: hwangdezang
    skip_cleanup: true
    local_dir: s3_upload
    upload-dir: travis
    on:
      branch: master
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: hwangdezang
    key: travis/latest.zip
    application: TravisJavaSample
    deployment_group: DezangSampleDG
    region: ap-northeast-2
    on:
      branch: master