version: 0.0
os: linux
files:
  - source: build/libs/gs-travis-java.jar
    destination: /home/ec2-user
hooks:
  ApplicationStop:
    - location: /aws/deploy-scripts/stop_server.sh
      runas: root
  BeforeInstall:
    - location: /aws/deploy-scripts/install_dependancy.sh
      runas: root
  ApplicationStart:
    - location: /aws/deploy-scripts/start_server.sh
      runas: root